name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout 馃泿锔�
        uses: actions/checkout@v3

      - name: Setup Node.js 鈿欙笍
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies 馃敡
        run: npm ci

      - name: Build 馃彈锔�
        run: npm run build
        env:
          # If you want to bake the API key into the build (Not recommended for public repos)
          # API_KEY: ${{ secrets.API_KEY }} 
          CI: false

      - name: Deploy 馃殌
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages
